# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 19:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomie',
            name='roomieAge',
            field=models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(130)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomie',
            name='roomieGender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomie',
            name='roomieGenderOther',
            field=models.BooleanField(default=False),
        ),
    ]
