# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_roomie_roomie'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sleep',
            field=models.CharField(default='Early Bird', max_length=255),
        ),
    ]
