# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_userprofile_sleep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='lon',
        ),
    ]
