# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-12 15:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_auto_20161004_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='age',
        ),
        migrations.AddField(
            model_name='apartment',
            name='ageMax',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(130)]),
        ),
        migrations.AddField(
            model_name='apartment',
            name='ageMin',
            field=models.IntegerField(default=17, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(130)]),
        ),
    ]
