# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-22 04:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_auto_20161012_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomie',
            name='roomieAge',
        ),
        migrations.AddField(
            model_name='roomie',
            name='roomieAgeMax',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(130)]),
        ),
        migrations.AddField(
            model_name='roomie',
            name='roomieAgeMin',
            field=models.IntegerField(default=17, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(130)]),
        ),
    ]
