# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0008_auto_20161022_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
    ]
