# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0009_auto_20161026_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='occupant',
            field=models.BooleanField(default=True),
        ),
    ]
